services:
  fortune-front:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - restaurant-search-network

networks:
  restaurant-search-network:
    external: true
